### ISSUE TITLE
App not identified on recent updates - media_title disappears after a while

### ISSUE THREAD

**Issue by antonio1475** [ollo69/ha-samsungtv-smart#228] opened 2023-02-02 21:16 UTC
Hello,

After the recent updates (0.11 I would say), which has many releases mentioning app identification improvements, the running app (especially Plex) recognition stops working for me. I see that:

1. The media_title attribute disappears after a few minutes
2. media_content_type is now video instead of app
3. Source says TV/HDMI instead of Plex (when app_id is clearly still Plex  or whatever app I'm using).

v0.10.0:
![image](https://user-images.githubusercontent.com/63130724/216448306-6f77558b-b677-4811-917b-dd4564f8a806.png)
Stable for minutes (indefinitely as far as I experienced).

v0.11.5:
![image](https://user-images.githubusercontent.com/63130724/216450583-1e21cb9d-c3ba-4138-8748-2037a7523e12.png)
If the media_title even appears (many times it doesn't), it disappears after a few minutes. The funny thing is that app_id is still there.

**Diagnostics:**
[v0.10.0.json.txt](https://github.com/ollo69/ha-samsungtv-smart/files/10573442/v0.10.0.json.txt)
[v0.11.5.json.txt](https://github.com/ollo69/ha-samsungtv-smart/files/10573470/v0.11.5.json.txt)

**Additional information:**
I have this Application List set up since a long time ago:
```
MiTele: BTqpJutesE.Mitele
Netflix: org.tizen.netflix-app
Plex: kIciSQlYEM.plex
YouTube: 9Ur5IzDKqV.TizenYouTube
Prime Video: org.tizen.primevideo
```

Happy to do whatever troubleshooting is needed or uplaod further logs.
Thank you

**Comment by ollo69** [comment] 2023-02-02 22:23
Issue here is related to application list, because are missing the native application ID. I don't know app id for `MiTele`, but for all the others the correct list should be:

```
Netflix: 3201907018807/org.tizen.netflix-app
Plex: 3201512006963/kIciSQlYEM.plex
YouTube: 111299001912/9Ur5IzDKqV.TizenYouTube
Prime Video: 3201512006785/org.tizen.primevideo
```

I will think about this kind of app list, but you should be able to fix the issue just updating you application list as described above.

**Comment by antonio1475** [comment] 2023-02-02 22:54
Very interesting. It does fix it inmediately, thank you.
The list worked in older versions and I was not aware that numerical is now necessary with newer versions of the integration. Is that a side effect of the recent app identification improvements?

I'm still consfused as to why when an app isn't added in app_list, all attributes appear as they did before (or at least media_title):
![image](https://user-images.githubusercontent.com/63130724/216465958-943bf028-70f4-4c95-900a-ae9ea9bfdd83.png)

But when the app is added to app_list
![image](https://user-images.githubusercontent.com/63130724/216466097-15d3bd56-392b-4851-92c1-0df3625e6280.png)
It worked for a few seconds (showed media_title and my custom logo) after saving - not long enough to screenshot, but then the attributes like media_title disappeared (different behaviour than older versions).

I'm unable to see the numerical ID for apps like MiTele as described in [App_list.md](https://github.com/ollo69/ha-samsungtv-smart/blob/master/docs/App_list.md) - only BTqpJutesE.Mitele shows in both app_id and media_title (when media_title appears).
![image](https://user-images.githubusercontent.com/63130724/216468591-b8eff202-7191-44ae-b235-ffe6b3fbcd81.png)


In any case, thank you!

**Comment by ollo69** [comment] 2023-02-02 23:07
The recent update give priority to information provided by the TV (numeric app id) to be faster and to avoid some cases where SmartThings do not update properly the app id. Honestly I never tested the condition provided by you where only SmartThings app id is provided, I do not esclude a possible bug in this case. I will make some test when I will have some available time.
Keep this issue open so that I will refer to it for future related commits.

To get the app id MiTele, you could try to check the advanced option "Show app list in log file". This not works for all TV models, but if works for your model you will find app id for all installed apps in HA log. Please note that log level must be at least `info` level.

**Comment by antonio1475** [comment] 2023-02-02 23:18
Understood, thanks!

Regarding the numerical id, I removed the app_list, set the Load apps to All Apps, checked Dump app_list in logs, and defined in configuration.yaml
```
logger:
  default: info
```
Restarted HA, no apps in log. Restarted TV, same.
The only related line is `2023-02-03 00:13:53.475 INFO (MainThread) [custom_components.samsungtv_smart.media_player] Samsung TV: loaded sources list from SmartThings: {'TV': 'ST_TV'}
`
I believe I did all the steps, so my TV is not reporting the apps. I'll try the scanning HTTP although I don't understand it yet.

Anyway, this is very minor so I'll stop bothering you. Thanks again, your integration is the only actual saviour for Samsung TV in HA!

**Comment by ollo69** [comment] 2023-02-05 14:30
I did some test on my TV, is working properly also using only the SmartThings app ID. Because at the end the solution is provide also the numeric appID and I'm not able to reproduce the issue, I close this. If you will have other problems, please open a new one.

**Closed by ollo69** 2023-02-05 14:30 UTC
