### ISSUE TITLE
TV Sources Missing Plex

### ISSUE THREAD

**Issue by zeieri** [ollo69/ha-samsungtv-smart#210] opened 2023-01-01 07:45 UTC
Hi there!

Excellent integration! Super excited about it!

We mainly use plex. At first, Plex showed up in the sources so I made a button to change to the app on command without having to go to home and select the app.

Now, plex is missing from the sources even though it is still installed! Code in HA is:

tap_action:
  action: call-service
  haptic: medium
  service: media_player.select_source
  service_data:
    entity_id: media_player.living_room_tv
    source: Plex - Free Movies ＆ TV

Any idea as to why it would no longer show in sources?

Thanks!

**Comment by ollo69** [comment] 2023-01-01 16:09
Is it configured in the app list? What do you mean when you say `Now, plex is missing`? Missing compared to what?

**Comment by zeieri** [comment] 2023-01-01 19:07
In the sources drop down for the TV in devices, plex is no longer listed.

What do you mean by configured in the app list? The app is installed on the TV and being used. It shows in the installed apps listing under Apps in Tizen OS.

Thanks!

**Comment by ollo69** [comment] 2023-01-01 21:01
You could manually configure an applications list because not all TV models return the list of installed apps, but I suppose that you didn't
So probably the issue is in this configuration option for which default value was recently changed:

![image](https://user-images.githubusercontent.com/60491700/210184321-cfa37542-efc6-4a2e-8a4b-182dfc9cece0.png)

You should set to `All Apps` and probably you issue will be fixed.
I will try to add Plex to the list of "standard app" so that Plex app will be available also using the option `Default apps`

**Comment by ollo69** [comment] 2023-01-25 19:42
I just added Plex to default apps, and anyway now All Apps is the default setting. I close this because should be fixed and I don't receive any feed-back from 3 weeks.

**Closed by ollo69** 2023-01-25 19:42 UTC
