### ISSUE TITLE
Turn on using SmartThings

### ISSUE THREAD

**Issue by VVlasy** [ollo69/ha-samsungtv-smart#55] opened 2021-01-18 13:46 UTC
**Is your feature request related to a problem? Please describe.**
Turning TV on using Wake on lan is unreliable

**Describe the solution you'd like**
SmartThings has an API to control the TV power state. Add a checkbox to settings to allow users to select which way they prefer the turning on action to occur.

Local - Wake On Lan
Remote - SmartThings
Both - Send both request at same time? Or Maybe try first Wake On Lan, wait, if TV appears still off use SmartThings

**Describe alternatives you've considered**
I considered raising the sent packet count for Wake On Lan, but in my case that would still not help as setting it to 20 and pressing the button 20 times before the TV turns on seems like too many packets.

**Comment by ollo69** [comment] 2021-01-18 15:26
Power control by SmartThings do not work in 98% of cases. The problem is that SamsungTV normally deactivate the network interface and TV is reachable at all, the WOL packet is the only way to turn it on.
WOL work perfect for me but I understand that it doesn't for you. How is your TV connected to the the LAN? And how is HA connected to the LAN? Are you using separated VLAN / Docker configuration?

**Comment by VVlasy** [comment] 2021-01-18 15:30
TV is connected using wireless, as I had issues turning it on/off when wired.

Good point about the home assistant which I currently have connected wirelessly, I will try again once wired.

No VLANs.

**Comment by ollo69** [comment] 2021-01-18 17:31
> TV is connected using wireless, as I had issues turning it on when wired.
You had issue using SmartThings? Did you try if instead WOL works using wired connection?

> Are you sure about the SmartThings power control not working in 98% of cases? Am I the exception? Alexa always turns the TV on, on her first try via SmartThings, no matter how long the TV has been turned off for. I have the same experience using the SmartThings app when I connect to LTE to prevent local connection.

This is the most of the feed-back that I received, but may be SmartThings works using wireless connection and not wired, and may be most of my feed-back are related to TV with wired connection. Could you make some test and report?

**Comment by ollo69** [comment] 2021-01-24 15:10
I did some test, really seems that SmartThings is able to turn on TV only when using Wireless Connection.
In any case WOL packet is normally fine when using wired connection.
In last release I added a configuration option to choose the method to use to turn on TV.

**Comment by VVlasy** [comment] 2021-01-24 15:12
That's great. Thank you! I was having a hard time sourcing a long cable to test wired connection. Good finding that. Although I don't understand why it works on wireless not wired.... Samsung things

**Comment by VVlasy** [comment] 2021-01-24 15:36
Btw I think your implementation should replace the default Samsung TV component in Home Assistant.

**Comment by ollo69** [comment] 2021-01-24 15:55
> Btw I think your implementation should replace the default Samsung TV component in Home Assistant.

Thanks, but seems that HA teams do not like to have standard component that use local and cloud implementation at the same time, so this will probably remain a custom component.

Please remember to close this issue if the implementation work properly, or report here any problem in case.

**Closed** 2021-01-24 15:57 UTC
Labels: Feature Request
