### ISSUE TITLE
Current States - No states found

### ISSUE THREAD

**Issue by Bagunda** [ollo69/ha-samsungtv-smart#140] opened 2022-03-09 10:15 UTC
Current States - No states found

SmartThings Device ID.

Go [here](https://graph-eu01-euwest1.api.smartthings.com/device/list) and login with your SmartThings credential

And there is "Current States - No states found"

![2022-03-09_13-11-05](https://user-images.githubusercontent.com/16766521/157420744-03cd555e-61a6-40f0-8b2b-e111b7ed27d7.png)

**Comment by ollo69** [comment] 2022-03-09 11:49
Please fill information required by template when opening a new issue. Here is not possible to understand what is the problem. I close this issue, open a new one with required details

**Closed by ollo69** 2022-03-09 11:49 UTC

**Comment by Bagunda** [comment] 2022-03-10 15:19
> Please fill information required by template when opening a new issue. Here is not possible to understand what is the problem. I close this issue, open a new one with required details

 - TV model: Samsung AU7500 - It's on the screenshot

I don't know what to say anymore.
It didn't even come to Home Assistant.

**Comment by ollo69** [comment] 2022-03-10 16:25
This is the template:

**Describe the bug**
A clear and concise description of what the bug is.

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):
 - Home Assistant version installed:
 - Component version installed:
 - Last know working version:
 - TV model:

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**
Add any other context about the problem here.

## On this issue even the description of the problem is not present!!!
If you need clarification on HA or how open issue in git, refer to HA blog or search on internet 
Now this issue is closed, if you still have problem open a new one and compile all possible part in the issue template, thanks👍
